### ISSUE TITLE
Investigate how Postman should be used for testing and how it should be paid for

### ISSUE THREAD

**Issue by llwaterhouse** [cisagov/LME#147]

**Comment by llwaterhouse** [comment]
We're currently investigating testing tools and one of the tools in question is Postman.  We want to see if using Postman's CLI functionality is worth paying for Postman instead of writing code ourselves for the API testing.

ECS currently has Postman in its Company Portal.  What version of Postman does it have?  Is it sufficient to use for testing now?If ECS comes off the project, how will Postman be transitioned to be paid for by the contract?

**Comment by llwaterhouse** [comment]
Thank you for your suggestions.  We will start researching these options.

**Comment by rishagg01** [comment]
Thank you Dmytro for your suggestions.

I did an evaluation on Hoppscotch and Bruno.
Hoppscotch was not right candidate for us since it only provides user interface to make HTTP requests. We needed more features including automated testing, assertions and team collaboration. Bruno seems to have all of these features and since it is also open source, it seems right candidate to do further exploration.

This was very helpful and once again Thank you very much for pointing us into this direction.

**Comment by dkorzhevin** [comment]
@rishagg01 glad to help!

**Comment by llwaterhouse** [comment]
Because of company policy, we are unable to install Bruno.

We're now using Python directly for the tests.
