### ISSUE TITLE
ElasticSearch Container crash every few seconds

### ISSUE THREAD

**Issue by LeitLei** [cisagov/LME#15]
My ElasticSearch container crash every few seconds after Updating from 0.5.1 to 1.0
In the logs I can see the following error:

> Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore
> {"@timestamp":"2023-10-30T10:21:48.331Z", "log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"loggingmadeeasy-es","error.type":"java.lang.IllegalStateException","error.message":"Unable to access 'path.repo' (/usr/share/elasticsearch/backups)","error.stack_trace":"java.lang.IllegalStateException: Unable to access 'path.repo' (/usr/share/elasticsearch/backups)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:66)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:252)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Security.createPermissions(Security.java:178)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Security.configure(Security.java:125)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Elasticsearch.initPhase2(Elasticsearch.java:188)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:66)\nCaused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/backups\n\tat java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)\n\tat java.base/sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:355)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:326)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:64)\n\t... 5 more\n"}
> ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/loggingmadeeasy-es.log

Any idea, how can I fix this? I was follow exactly your upgrade guide.

Docker version: 20.10.23, build 7155243
Ubuntu 20.04.6 LTS

Folder /usr/share/elasticsearch/ doesn't exist. So there are no log files there.

Best Regards
Patrick

**Comment by llwaterhouse** [comment]
We suspect that the issue is that the /usr/share/elasticsearch/backups folder (which is mounted to /opt/lme/backups on the host) doesn't have the proper permissions that the current LME requires.

Grab the container name that is displaying the errors with:

`sudo docker ps -a `

We are assuming your error output was derived from the command

`sudo docker logs -f [elastic_container_name]`

You can solve the permissions issue by doing the following:

1. `sudo chown -R 1000:1000 /opt/lme/backups`
 that should make sure the backups folder is owned by the same userid as the container userid.
2. ` sudo docker exec -it [elastic_container_name] /bin/bash.  `
using the appropriate name for the container that is erroring
3. In the container shell you creeated in Step 2, run the following to check you have the correct permissions
` touch /usr/share/elasticsearch/backups`
4.  If that errors with a permission issue, run
`sudo chown 1000:1000 /opt/lme/`  
since you probably can't read the directory of lme
5. Try Step 3 again
6. This should fix your issue. If not, please reach out again.

**Comment by LeitLei** [comment]
Thanks a lot. Step 1 to 3 fix the issue.

By the way:
`cd /opt/lme/`
`sudo ./dashboard_update.sh`
referred at https://github.com/cisagov/LME/blob/main/docs/markdown/maintenance/upgrading.md doesn't work (for me).

But this work:
`cd /opt/lme/`
`sudo -s`
`bash ./dashboard_update.sh`

Maybe a mistake in your manual?

Best Regards
Patrick
